# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from unittest.mock import MagicMock

from a2a.types import AgentCapabilities, AgentCard, TaskStatusUpdateEvent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.sessions import InMemorySessionService
from google.protobuf import json_format

from app.remote_agents import GDARemoteAgent


def _create_mock_gda_agent() -> GDARemoteAgent:
    card = AgentCard(
        name="coffee_agent",
        description="Coffee business agent",
        version="1.0.0",
        capabilities=AgentCapabilities(streaming=True),
        default_input_modes=["text"],
        default_output_modes=["text"],
        skills=[],
    )
    return GDARemoteAgent(
        agent_resource_name="projects/test-proj/locations/global/dataAgents/coffee-agent",
        agent_card=card,
        google_auth=MagicMock(),
        httpx_client=MagicMock(),
    )


def test_extract_followup_questions_user_payload() -> None:
    item = {
        "data": {
            "data": {
                "recommendedQuestionsResponse": {
                    "questions": [
                        '"Analyze the revenue generated by each coffee truck to understand individual contributions."',
                        '"Forecast the weekly revenue for the next 4 weeks."',
                    ]
                }
            }
        },
        "metadata": {
            "mimeType": "application/json+suggestions",
            "gda_message": {
                "messageId": "synthetic-dcd2bd84-e150-43d4-ba41-0a27154c1e42",
                "type": "text",
                "subType": "followup_questions",
            },
        },
    }

    questions = GDARemoteAgent._extract_followup_questions(item)
    assert questions == [
        "Analyze the revenue generated by each coffee truck to understand individual contributions.",
        "Forecast the weekly revenue for the next 4 weeks.",
    ]


def test_extract_followup_questions_variations() -> None:
    # Single data nesting with snake_case
    item_snake = {
        "data": {
            "recommended_questions_response": {
                "questions": ["Question 1", "Question 2"]
            }
        }
    }
    assert GDARemoteAgent._extract_followup_questions(item_snake) == [
        "Question 1",
        "Question 2",
    ]

    # JSON string in data
    item_json_str = {
        "data": '{"recommendedQuestionsResponse": {"questions": ["Q1", "Q2"]}}'
    }
    assert GDARemoteAgent._extract_followup_questions(item_json_str) == ["Q1", "Q2"]

    # Empty data
    assert GDARemoteAgent._extract_followup_questions({}) == []


def test_custom_status_parser_followup_questions_proto() -> None:
    agent = _create_mock_gda_agent()
    session_service = InMemorySessionService()
    session = session_service.create_session_sync(user_id="test_user", app_name="test_app")
    ctx = InvocationContext(session=session, session_service=session_service, invocation_id="inv-1")

    payload = {
        "taskId": "4ac3c99f-3397-41c3-8401-de52a02976f6",
        "contextId": "projects/liuchristie-142-20250922213141/locations/global/conversations/468b41fa-b278-4465-9e75-3e455c982ed5",
        "status": {
            "state": "TASK_STATE_WORKING",
            "message": {
                "messageId": "synthetic-dcd2bd84-e150-43d4-ba41-0a27154c1e42",
                "contextId": "projects/liuchristie-142-20250922213141/locations/global/conversations/468b41fa-b278-4465-9e75-3e455c982ed5",
                "taskId": "4ac3c99f-3397-41c3-8401-de52a02976f6",
                "role": "ROLE_AGENT",
                "parts": [
                    {
                        "data": {
                            "data": {
                                "recommendedQuestionsResponse": {
                                    "questions": [
                                        '"Analyze the revenue generated by each coffee truck to understand individual contributions."',
                                        '"Forecast the weekly revenue for the next 4 weeks."',
                                    ]
                                }
                            }
                        },
                        "metadata": {
                            "mimeType": "application/json+suggestions",
                            "gda_message": {
                                "messageId": "synthetic-dcd2bd84-e150-43d4-ba41-0a27154c1e42",
                                "type": "text",
                                "subType": "followup_questions",
                            },
                        },
                    }
                ],
                "metadata": {
                    "type": {"name": "text", "subType": "followup_questions"}
                },
            },
        },
    }

    event_proto = json_format.ParseDict(
        payload, TaskStatusUpdateEvent(), ignore_unknown_fields=True
    )
    adk_event = agent.custom_status_parser(
        update=event_proto,
        agent_name=agent.name,
        ctx=ctx,
        part_converter=MagicMock(),
    )

    assert adk_event is not None
    assert adk_event.author == "coffee_agent"
    assert adk_event.partial is True
    assert len(adk_event.content.parts) == 1

    expected_text = (
        "**Recommended Follow Up Questions:**\n"
        "* Analyze the revenue generated by each coffee truck to understand individual contributions.\n"
        "* Forecast the weekly revenue for the next 4 weeks."
    )
    assert adk_event.content.parts[0].text == expected_text

    # Verify context_id was recorded in session state and state_delta
    expected_context_id = (
        "projects/liuchristie-142-20250922213141/locations/global/conversations/468b41fa-b278-4465-9e75-3e455c982ed5"
    )
    assert session.state.get("gda_context_coffee_agent") == expected_context_id
    assert adk_event.actions.state_delta.get("gda_context_coffee_agent") == expected_context_id


def test_custom_status_parser_followup_questions_dict() -> None:
    agent = _create_mock_gda_agent()
    session_service = InMemorySessionService()
    session = session_service.create_session_sync(user_id="test_user", app_name="test_app")
    ctx = InvocationContext(session=session, session_service=session_service, invocation_id="inv-1")

    payload_dict = {
        "statusUpdate": {
            "taskId": "4ac3c99f-3397-41c3-8401-de52a02976f6",
            "contextId": "projects/liuchristie-142-20250922213141/locations/global/conversations/468b41fa-b278-4465-9e75-3e455c982ed5",
            "status": {
                "state": "TASK_STATE_WORKING",
                "message": {
                    "messageId": "synthetic-dcd2bd84-e150-43d4-ba41-0a27154c1e42",
                    "contextId": "projects/liuchristie-142-20250922213141/locations/global/conversations/468b41fa-b278-4465-9e75-3e455c982ed5",
                    "taskId": "4ac3c99f-3397-41c3-8401-de52a02976f6",
                    "role": "ROLE_AGENT",
                    "content": [
                        {
                            "data": {
                                "data": {
                                    "recommendedQuestionsResponse": {
                                        "questions": [
                                            '"Analyze the revenue generated by each coffee truck to understand individual contributions."',
                                            '"Forecast the weekly revenue for the next 4 weeks."',
                                        ]
                                    }
                                }
                            },
                            "metadata": {
                                "mimeType": "application/json+suggestions",
                                "gda_message": {
                                    "messageId": "synthetic-dcd2bd84-e150-43d4-ba41-0a27154c1e42",
                                    "type": "text",
                                    "subType": "followup_questions",
                                },
                            },
                        }
                    ],
                    "metadata": {
                        "type": {"name": "text", "subType": "followup_questions"}
                    },
                },
            },
        }
    }

    adk_event = agent.custom_status_parser(
        update=payload_dict,
        agent_name=agent.name,
        ctx=ctx,
        part_converter=MagicMock(),
    )

    assert adk_event is not None
    assert adk_event.author == "coffee_agent"
    assert adk_event.partial is True
    assert len(adk_event.content.parts) == 1

    expected_text = (
        "**Recommended Follow Up Questions:**\n"
        "* Analyze the revenue generated by each coffee truck to understand individual contributions.\n"
        "* Forecast the weekly revenue for the next 4 weeks."
    )
    assert adk_event.content.parts[0].text == expected_text

    expected_context_id = (
        "projects/liuchristie-142-20250922213141/locations/global/conversations/468b41fa-b278-4465-9e75-3e455c982ed5"
    )
    assert session.state.get("gda_context_coffee_agent") == expected_context_id
    assert adk_event.actions.state_delta.get("gda_context_coffee_agent") == expected_context_id



def test_custom_status_parser_thought() -> None:
    agent = _create_mock_gda_agent()
    session_service = InMemorySessionService()
    session = session_service.create_session_sync(user_id="test_user", app_name="test_app")
    ctx = InvocationContext(session=session, session_service=session_service, invocation_id="inv-1")

    payload = {
        "status": {
            "state": "TASK_STATE_WORKING",
            "message": {
                "parts": [
                    {
                        "text": "Thinking about coffee sales...",
                        "metadata": {"gda_message": {"subType": "thought"}},
                    }
                ]
            },
        }
    }
    event_proto = json_format.ParseDict(
        payload, TaskStatusUpdateEvent(), ignore_unknown_fields=True
    )
    adk_event = agent.custom_status_parser(
        update=event_proto,
        agent_name=agent.name,
        ctx=ctx,
        part_converter=MagicMock(),
    )

    assert adk_event is not None
    assert len(adk_event.content.parts) == 1
    assert adk_event.content.parts[0].text == "Thinking about coffee sales..."
    assert getattr(adk_event.content.parts[0], "thought", False) is True
